// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAgs06ZFgv4TEmrtlJFHNoGIbSHP2tqo',
    appId: '1:402610682153:web:9747dbca1accc7ab02df38',
    messagingSenderId: '402610682153',
    projectId: 'gift-mate-54748293',
    authDomain: 'gift-mate-54748293.firebaseapp.com',
    storageBucket: 'gift-mate-54748293.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2MleAJ7vANZY12hMlfvSn81SOaQ2DFM',
    appId: '1:402610682153:android:62c8e371b020d95902df38',
    messagingSenderId: '402610682153',
    projectId: 'gift-mate-54748293',
    storageBucket: 'gift-mate-54748293.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArviYcHXVORKke8mRq9RNYWkrX1hXZHl8',
    appId: '1:402610682153:ios:9459b7fa6271db9a02df38',
    messagingSenderId: '402610682153',
    projectId: 'gift-mate-54748293',
    storageBucket: 'gift-mate-54748293.firebasestorage.app',
    iosBundleId: 'gift-mate.app',
  );
}
